name: downloader_flutter
description: File downloader built for Flutter, supporting Android & iOS.
version: 0.0.5
homepage: https://github.com/Anandhakrishnan-CodeBlock/downloader_flutter.git
issue_tracker: https://github.com/Anandhakrishnan-CodeBlock/downloader_flutter/issues
maintainer: Anandhakrishnan

environment:
  sdk: ^3.10.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.anandhakrishnan.codeblock.downloader_flutter
        pluginClass: DownloaderFlutterPlugin
      ios:
        pluginClass: DownloaderFlutterPlugin
